name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    name: ${{ matrix.session }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        session: [pre-commit, lint, fmt, coverage]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install nox
        run: uv tool install nox

      - name: Run ${{ matrix.session }}
        run: nox -p 3.13 -s ${{ matrix.session }}

      - name: Upload coverage report
        if: matrix.session == 'coverage'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: xransum/pokerena

  docs:
    name: docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install nox
        run: uv tool install nox

      - name: Build docs
        run: nox -p 3.13 -s docs
